/**
 * Turns the designer's package into the two things the app actually ships:
 * a TypeScript module of SVG sources, and the app icon.
 *
 * The SVGs go into the bundle as strings, not into `public`, because every
 * one of them is drawn onto the canvas: a `data:` URI keeps `toDataURL`
 * working, and a file URL would be one more thing that can 404 mid-export.
 *
 * Run it after the designer sends a new package:
 *   node scripts/build-brand.mjs
 */

import fs from 'node:fs'
import path from 'node:path'

const PKG = 'assets/brand/alexey-sots-selected'
const read = (p) => fs.readFileSync(path.join(PKG, p), 'utf8')

/** The watermark file is one stamp repeated; pull the first one out of it. */
function firstStamp() {
  const src = read('watermarks/as-watermark-light.svg')
  const open = /<g transform="translate\(\d+ \d+\) scale\(1\)" opacity="[\d.]+">/.exec(src)
  if (!open) throw new Error('no stamp group in the watermark file')
  let depth = 1
  let i = open.index + open[0].length
  const tag = /<g\b|<\/g>/g
  tag.lastIndex = i
  let end = i
  for (;;) {
    const m = tag.exec(src)
    if (!m) throw new Error('unbalanced groups')
    depth += m[0] === '<g' ? 1 : -1
    if (depth === 0) {
      end = m.index
      break
    }
  }
  const inner = src.slice(open.index + open[0].length, end)
  // the stamp box comes from design-tokens.json, and the opacity is left off:
  // the app applies it once per preset, exactly as the package asks
  const [w, h] = tokens.watermark.stampSize
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}">${inner}</svg>`
}

const tokens = JSON.parse(read('design-tokens.json'))

/** every SVG we ship must carry width and height, or Safari draws nothing */
function checked(name, svg) {
  if (!/^<svg[^>]*\swidth="\d/.test(svg) || !/^<svg[^>]*\sheight="\d/.test(svg)) {
    throw new Error(`${name}: the root <svg> needs explicit width and height`)
  }
  if (/<image|xlink:href|url\(http|<script|@font-face|font-family/.test(svg)) {
    throw new Error(`${name}: external reference or live font found`)
  }
  return svg.replace(/\n\s*/g, '').trim()
}

const power = []
for (let i = 1; i <= 9; i++) {
  const n = String(i).padStart(2, '0')
  power.push(checked(`strength-${n}`, read(`power/strength-${n}.svg`)))
}

const out = `/**
 * Brand assets as SVG source, generated by scripts/build-brand.mjs from
 * assets/brand/alexey-sots-selected. Do not edit by hand: edit the package.
 *
 * They are strings rather than files under public/ because each one is drawn
 * onto the canvas through a \`data:\` URI, which keeps the canvas untainted and
 * \`toDataURL\` working - the same reason this project has no CDN fonts.
 */

/** one "АС + Алексей Соць" signature, ${tokens.watermark.stampSize.join(' x ')} units, opacity left to the caller */
export const STAMP_SVG = ${JSON.stringify(checked('stamp', firstStamp()))}

/** the monogram alone, 100 x 100 */
export const SIGN_WHITE_SVG = ${JSON.stringify(checked('sign-white', read('logos/as-sign-white.svg')))}

/** monogram + name in a row, 306 x 72 */
export const LOGO_HORIZONTAL_WHITE_SVG = ${JSON.stringify(checked('horizontal-white', read('logos/as-horizontal-white.svg')))}

/** the nine states of the strength indicator, index 0 = 0,5 and index 8 = 4,5 */
export const POWER_SVGS: readonly string[] = [
${power.map((s) => '  ' + JSON.stringify(s) + ',').join('\n')}
]

/** the designer's artboard the watermark coordinates are written in */
export const WATERMARK_ARTBOARD = {
  cloth: { x: ${tokens.watermark.cloth[0]}, y: ${tokens.watermark.cloth[1]}, w: ${tokens.watermark.cloth[2]}, h: ${tokens.watermark.cloth[3]} },
  columns: ${tokens.watermark.columns},
  stampW: ${tokens.watermark.stampSize[0]},
  stampH: ${tokens.watermark.stampSize[1]},
} as const

/** the indicator's own artboard, 140 x 88 = one eighth of the designer's cloth */
export const POWER_ARTBOARD = { w: ${tokens.indicator.width}, h: ${tokens.indicator.height} } as const

export const BRAND = {
  navy: '${tokens.colors.navy}',
  cream: '${tokens.colors.cream}',
  white: '${tokens.colors.white}',
} as const
`
fs.mkdirSync('src/brand', { recursive: true })
fs.writeFileSync('src/brand/assets.ts', out)

// the app icon: the monogram on a navy tile, so it reads on a light tab bar too
const sign = read('logos/as-sign-white.svg')
const signPaths = sign.slice(sign.indexOf('</title>') + 8, sign.lastIndexOf('</svg>'))
fs.mkdirSync('public/brand', { recursive: true })
fs.writeFileSync(
  'public/brand/icon.svg',
  `<svg xmlns="http://www.w3.org/2000/svg" width="128" height="128" viewBox="0 0 128 128">` +
    `<rect width="128" height="128" rx="26" fill="${tokens.colors.navy}"/>` +
    `<g transform="translate(14 14) scale(1.0)">${signPaths}</g></svg>\n`,
)

fs.mkdirSync('public/fonts', { recursive: true })
fs.copyFileSync(path.join(PKG, 'fonts/Manrope-variable.woff2'), 'public/fonts/manrope.woff2')
fs.copyFileSync(path.join(PKG, 'fonts/OFL.txt'), 'public/fonts/LICENSE-Manrope.txt')

const kb = (s) => Math.round(s.length / 102.4) / 10
console.log(
  `src/brand/assets.ts written: stamp ${kb(firstStamp())} KB, ${power.length} power states ` +
    `${kb(power.join(''))} KB, logo ${kb(read('logos/as-horizontal-white.svg'))} KB`,
)
console.log('public/brand/icon.svg, public/fonts/manrope.woff2, LICENSE-Manrope.txt written')
